name: Build PandaBattleship API

on:
  pull_request:
    branches: [ main ]
    paths: &build-api-paths
      - 'PandaBattleship.API/**'
  push:
    branches: [ main ]
    paths: *build-api-paths

jobs:
  build:
    uses: ./.github/workflows/reusable-build-api.yml