name: Build PandaBattleship API

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'PandaBattleship.API/**'
      - 'PandaBattleship.ServiceDefaults/**'
      - '.github/workflows/build-api.yml'
      - '.github/workflows/reusable-build-api.yml'

jobs:
  build:
    name: API
    uses: ./.github/workflows/reusable-build-api.yml